;             
CREATE SCHEMA IF NOT EXISTS SCHHRS AUTHORIZATION USRHRS;
SET SCHEMA SCHHRS;
GRANT ALL ON SCHEMA SCHHRS TO USRHRS;      
CREATE SEQUENCE PUBLIC.SEQ_USERS START WITH 1 MAXVALUE 99999; 
CREATE SEQUENCE PUBLIC.SEQ_ROLES START WITH 1 MAXVALUE 99999; 
CREATE SEQUENCE PUBLIC.SEQ_PERMISSSIONS START WITH 1 MAXVALUE 99999;          
CREATE CACHED TABLE PUBLIC.USERS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_USERS) NOT NULL,
    ROLE VARCHAR(24) NOT NULL,
    PASSWORD VARCHAR(24) NOT NULL,
    STATUS ENUM('DISABLED','ENABLED') NOT NULL,
    PASS_EXPR DATE
);
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
CREATE CACHED TABLE PUBLIC.ROLES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_ROLES) NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    PERMISSION VARCHAR(32) NOT NULL
);    
ALTER TABLE PUBLIC.ROLES ADD CONSTRAINT PUBLIC.CONSTRAINT_4A PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLES;   
CREATE CACHED TABLE PUBLIC.PERMISSIONS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_PERMISSSIONS) NOT NULL,
    NAME VARCHAR NOT NULL,
    READ BOOL NOT NULL,
    WRITE BOOL NOT NULL,
    MODIFY BOOL NOT NULL,
    REMOVE BOOL NOT NULL,
    SAVE BOOL NOT NULL
);               
ALTER TABLE PUBLIC.PERMISSIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERMISSIONS;             
ALTER TABLE PUBLIC.ROLES ADD CONSTRAINT PUBLIC.CONSTRAINT_4A8 FOREIGN KEY(PERMISSION) REFERENCES PUBLIC.PERMISSIONS(ID) NOCHECK;              
