;             
CREATE USER IF NOT EXISTS USRHRS SALT '4849801d993f60e2' HASH 'd8261a20317b12807c789ac87b73e74cd4c5d02db33e84a7b52e751c79785ba1' ADMIN;       
CREATE USER IF NOT EXISTS SA SALT 'c2077af21353cc9e' HASH 'd10c1cfecf579056a2b127a8ba7d9dd12c56127f1d207a0f1ae8c0a2c50751e5' ADMIN;           
CREATE SCHEMA IF NOT EXISTS SCHHRS AUTHORIZATION USRHRS;      
CREATE SEQUENCE SCHHRS.SEQ_TRAINING START WITH 1 MAXVALUE 99999;              
CREATE SEQUENCE PUBLIC.SEQ_USERS START WITH 1 MAXVALUE 99999; 
CREATE SEQUENCE PUBLIC.SEQ_ROLES START WITH 1 MAXVALUE 99999; 
CREATE SEQUENCE PUBLIC.SEQ_PERMISSSIONS START WITH 1 MAXVALUE 99999;          
CREATE CACHED TABLE PUBLIC.USERS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_USERS) NOT NULL,
    ROLE VARCHAR(24) NOT NULL,
    PASSWORD VARCHAR(24) NOT NULL,
    STATUS ENUM('DISABLED','ENABLED') NOT NULL,
    PASS_EXPR DATE
);
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
CREATE CACHED TABLE PUBLIC.ROLES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_ROLES) NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    PERMISSION VARCHAR(32) NOT NULL
);    
ALTER TABLE PUBLIC.ROLES ADD CONSTRAINT PUBLIC.CONSTRAINT_4A PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLES;   
CREATE CACHED TABLE PUBLIC.PERMISSIONS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_PERMISSSIONS) NOT NULL,
    NAME VARCHAR NOT NULL,
    READ BOOL NOT NULL,
    WRITE BOOL NOT NULL,
    MODIFY BOOL NOT NULL,
    REMOVE BOOL NOT NULL,
    SAVE BOOL NOT NULL
);               
ALTER TABLE PUBLIC.PERMISSIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERMISSIONS;             
CREATE CACHED TABLE SCHHRS.TRAINING(
    ID INT DEFAULT (NEXT VALUE FOR SCHHRS.SEQ_TRAINING) NOT NULL,
    COMPANY VARCHAR(24) NOT NULL,
    FROM_DAY DATE NOT NULL,
    UNTIL_DAY DATE NOT NULL,
    PRICE DECIMAL NOT NULL,
    CONSENT BOOL NOT NULL,
    PLACE VARCHAR(24) NOT NULL,
    THEME VARCHAR(48) NOT NULL,
    USER_ID INT NOT NULL
);
ALTER TABLE SCHHRS.TRAINING ADD CONSTRAINT SCHHRS.CONSTRAINT_7 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM SCHHRS.TRAINING;
ALTER TABLE SCHHRS.TRAINING ADD CONSTRAINT SCHHRS.CONSTRAINT_7A FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(ID) NOCHECK;     
ALTER TABLE PUBLIC.ROLES ADD CONSTRAINT PUBLIC.CONSTRAINT_4A8 FOREIGN KEY(PERMISSION) REFERENCES PUBLIC.PERMISSIONS(ID) NOCHECK;              
GRANT ALL ON SCHEMA SCHHRS TO USRHRS;         
