SET IGNORECASE 1;             
;             
ALTER USER SA SET SALT '41aa162b20572f45' HASH '2d8b8c49eecde0b0b97675b777cfbd3c657d5f5a042172a9abe963c03d3f04b9';
CREATE USER IF NOT EXISTS HRS_USER SALT '602e49c9d8eb8bdd' HASH '36739355bb004cc9ae266202735535589428fd853c95d72491520c2dbb3562e5' ADMIN;
CREATE SCHEMA IF NOT EXISTS HRS_SCH AUTHORIZATION HRS_USER;   
CREATE SEQUENCE HRS_SCH.CONTRACTOR_SEQ START WITH 1 MAXVALUE 99999;           
CREATE SEQUENCE HRS_SCH.ROLES_SEQ START WITH 1 MAXVALUE 99999;
CREATE SEQUENCE HRS_SCH.PERMISSIONS_SEQ START WITH 1 MAXVALUE 99999;          
CREATE SEQUENCE HRS_SCH.INVOICE_SEQ START WITH 1 MAXVALUE 99999;              
CREATE SEQUENCE HRS_SCH.USERS_SEQ START WITH 1 MAXVALUE 99999;
CREATE SEQUENCE HRS_SCH.TRAINING_SEQ START WITH 1 MAXVALUE 99999;             
CREATE CACHED TABLE HRS_SCH."Users"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.USERS_SEQ) NOT NULL,
    "Role" VARCHAR_IGNORECASE(24) NOT NULL,
    "Pass" VARCHAR_IGNORECASE(24) NOT NULL,
    "Status" ENUM('DISABLED','ENABLED') NOT NULL,
    "Pass_Expire" DATE,
    "Username" VARCHAR_IGNORECASE(24),
    "e-mail" VARCHAR_IGNORECASE(24),
    "Pass_changed_date" DATE,
    "Login_last_success" DATE,
    "Login_last_failed" DATE,
    "Login_attempts_failed" INT
);
ALTER TABLE HRS_SCH."Users" ADD CONSTRAINT HRS_SCH.CONSTRAINT_4 PRIMARY KEY("Id");            
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Users";
CREATE CACHED TABLE HRS_SCH."Roles"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.ROLES_SEQ) NOT NULL,
    "Name" VARCHAR_IGNORECASE(32) NOT NULL,
    "Permission" VARCHAR_IGNORECASE(32) NOT NULL
);    
ALTER TABLE HRS_SCH."Roles" ADD CONSTRAINT HRS_SCH.CONSTRAINT_4B PRIMARY KEY("Id");           
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Roles";
CREATE CACHED TABLE HRS_SCH."Permissions"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.PERMISSIONS_SEQ) NOT NULL,
    "Name" VARCHAR_IGNORECASE NOT NULL,
    "Read" BOOL NOT NULL,
    "Write" BOOL NOT NULL,
    "Modify" BOOL NOT NULL,
    "Remove" BOOL NOT NULL,
    "Save" BOOL NOT NULL
);   
ALTER TABLE HRS_SCH."Permissions" ADD CONSTRAINT HRS_SCH.CONSTRAINT_A PRIMARY KEY("Id");      
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Permissions";          
CREATE CACHED TABLE HRS_SCH."Training"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.TRAINING_SEQ) NOT NULL,
    "Company" VARCHAR_IGNORECASE(24) NOT NULL,
    "From_Day" DATE NOT NULL,
    "Until_Day" DATE NOT NULL,
    "Price" DECIMAL NOT NULL,
    "Consent" BOOL NOT NULL,
    "Place" VARCHAR_IGNORECASE(24) NOT NULL,
    "Theme" VARCHAR_IGNORECASE(48) NOT NULL,
    "Author_Id" INT NOT NULL,
    "Cancelled" ENUM('No','Yes') NOT NULL,
    "No_of_seats" INT NOT NULL
);          
ALTER TABLE HRS_SCH."Training" ADD CONSTRAINT HRS_SCH.CONSTRAINT_4F PRIMARY KEY("Id");        
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Training";             
CREATE CACHED TABLE HRS_SCH."Users_Training_list"(
    "Training_ID" INT NOT NULL,
    "Users_ID" INT NOT NULL,
    "Note" VARCHAR_IGNORECASE(48),
    "Date_of_sign" DATE NOT NULL,
    "Cancelled" ENUM('No','Yes') NOT NULL,
    "Agreed" ENUM('No','Yes')
);       
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Users_Training_list";  
CREATE CACHED TABLE HRS_SCH."Contractor"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.CONTRACTOR_SEQ) NOT NULL,
    "Name" VARCHAR_IGNORECASE(48) NOT NULL,
    "Address" VARCHAR_IGNORECASE(32) NOT NULL,
    "NIP_Number" BIGINT NOT NULL,
    "REGON_Number" BIGINT NOT NULL,
    "Bank_Account_Number" VARCHAR_IGNORECASE(28) NOT NULL,
    "Payment_Form" VARCHAR_IGNORECASE(12) NOT NULL,
    "Active_Taxpayer_VAT_Tax" BOOL NOT NULL
);      
ALTER TABLE HRS_SCH."Contractor" ADD CONSTRAINT HRS_SCH.CONSTRAINT_9 PRIMARY KEY("Id");       
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Contractor";           
CREATE CACHED TABLE HRS_SCH."Invoice"(
    "Id" INT DEFAULT (NEXT VALUE FOR HRS_SCH.INVOICE_SEQ) NOT NULL,
    "Seller_Name" VARCHAR_IGNORECASE(48) NOT NULL,
    "Seller_Address" VARCHAR_IGNORECASE(32) NOT NULL,
    "Seller_NIP" BIGINT NOT NULL,
    "Seller_Account_Number" VARCHAR_IGNORECASE(28) NOT NULL,
    "Buyer_Name" VARCHAR_IGNORECASE(48) NOT NULL,
    "Buyer_Address" VARCHAR_IGNORECASE(32) NOT NULL,
    "Buyer_NIP" BIGINT NOT NULL,
    "Payment_Method" VARCHAR_IGNORECASE(12) NOT NULL,
    "Issue_Date" DATE NOT NULL,
    "Sale_Date" DATE NOT NULL,
    "Payment_Date" DATE NOT NULL,
    "Goods_Service" VARCHAR_IGNORECASE(48) NOT NULL,
    "Quantity" INT NOT NULL,
    "Net_Price" DECIMAL NOT NULL,
    TAX INT NOT NULL,
    "Gross_Price" DECIMAL NOT NULL,
    "Document_Issued" VARCHAR_IGNORECASE(24) NOT NULL
);   
ALTER TABLE HRS_SCH."Invoice" ADD CONSTRAINT HRS_SCH.CONSTRAINT_D PRIMARY KEY("Id");          
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Invoice";              
CREATE CACHED TABLE HRS_SCH."Contractor_Users"(
    "Contractor_ID" INT NOT NULL,
    "Users_ID" INT NOT NULL,
    "Note" VARCHAR_IGNORECASE(48),
    "Active_Worker" BOOL NOT NULL,
    "Participation" ENUM('No','Yes')
);            
-- 0 +/- SELECT COUNT(*) FROM HRS_SCH."Contractor_Users";     
ALTER TABLE HRS_SCH."Users_Training_list" ADD CONSTRAINT HRS_SCH.CONSTRAINT_DC FOREIGN KEY("Training_ID") REFERENCES HRS_SCH."Training"("Id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;    
ALTER TABLE HRS_SCH."Contractor_Users" ADD CONSTRAINT HRS_SCH.CONSTRAINT_DF FOREIGN KEY("Contractor_ID") REFERENCES HRS_SCH."Contractor"("Id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;   
ALTER TABLE HRS_SCH."Users_Training_list" ADD CONSTRAINT HRS_SCH.CONSTRAINT_DC2 FOREIGN KEY("Users_ID") REFERENCES HRS_SCH."Users"("Id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;         
ALTER TABLE HRS_SCH."Contractor_Users" ADD CONSTRAINT HRS_SCH.CONSTRAINT_DF5 FOREIGN KEY("Users_ID") REFERENCES HRS_SCH."Users"("Id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;            
ALTER TABLE HRS_SCH."Training" ADD CONSTRAINT HRS_SCH.CONSTRAINT_4FE FOREIGN KEY("Author_Id") REFERENCES HRS_SCH."Users"("Id") NOCHECK;       
ALTER TABLE HRS_SCH."Roles" ADD CONSTRAINT HRS_SCH.CONSTRAINT_4B7 FOREIGN KEY("Permission") REFERENCES HRS_SCH."Permissions"("Id") NOCHECK;   
GRANT ALL ON SCHEMA HRS_SCH TO HRS_USER;      
